(function(){
const $=id=>document.getElementById(id),defaults={name:'VOXEN FIGHTER',description:'WELCOME TO—VOXEN FIGHTER\n#VOXEN ANTI-DIMMING...',limit:'44',full:'0',members:'126',titleFont:'serif',format:'jpg'};let source='default',file=null,timer,busy=false,pending=false,lastKey='',blob=null,blobUrl=null,sourceSequence=0;
const segment=value=>[...new Intl.Segmenter('id',{granularity:'grapheme'}).segment(String(value))].map(x=>x.segment),shell=value=>"'"+String(value).replace(/'/g,"'\\''")+"'";
function values(){const p={};for(const key of Object.keys(defaults))p[key]=$(key).value;return p;}
function params(){const q=new URLSearchParams(values());if(source==='url')q.set('profile',$('profileUrl').value.trim());else if(source!=='upload')q.set('profile',source==='none'?'none':'default');return q;}
function endpoint(){const v=values();if(source==='default'&&Object.keys(defaults).every(k=>v[k]===defaults[k]))return '/ssgc';return '/ssgc?'+params();}
function key(){return JSON.stringify([endpoint(),source==='upload'?file&&[file.name,file.size,file.lastModified]:source]);}
function examples(){const p=values(),q=params(),url=location.origin+endpoint(),name='ssgc.'+p.format;$('count').textContent=segment(p.description).length+' / 2000';$('limit').disabled=p.full==='1';$('apiUrl').value=url;
const large=url.length>6000;let code;if(source==='upload')code='# POST multipart · letakkan foto di folder eksekusi\n'+['curl --fail --show-error '+shell(large?location.origin+'/ssgc':location.origin+'/ssgc?'+q),...(large?[...q].map(([k,v])=>'  --form-string '+shell(k+'='+v)):[]),'  -F '+shell('profile=@'+(file?.name||'foto.png')),'  -o '+shell(name)].join(String.fromCharCode(32,92,10));else if(large)code='# POST JSON otomatis · payload panjang di body\n'+['curl --fail --show-error '+shell(location.origin+'/ssgc'),'  -H '+shell('Content-Type: application/json'),'  --data-raw '+shell(JSON.stringify(Object.fromEntries(q))),'  -o '+shell(name)].join(String.fromCharCode(32,92,10));else code='curl --fail --show-error '+shell(url)+' -o '+shell(name);if(large)$('apiUrl').value=location.origin+'/ssgc';$('code').textContent=code;
const n=segment(p.description).length,l=Number(p.limit),cut=p.full!=='1'&&l>0&&n>l;$('descriptionHint').textContent=cut?'Preview menampilkan '+l+' dari '+n+' karakter + “… Baca selengkapnya”.':'Deskripsi ditampilkan penuh; tanpa link Baca selengkapnya.';if(lastKey!==key())$('download').disabled=true;}
function sourceMode(next){sourceSequence++;source=next;document.querySelectorAll('[data-profile]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.profile===next)));$('profileUrlFields').hidden=next!=='url';$('profileUpload').hidden=next!=='upload';$('profileUrl').disabled=next!=='url';examples();schedule();}
function valid(){return $('editor').checkValidity()&&!(source==='upload'&&!file)&&!(source==='url'&&!$('profileUrl').value.trim());}
function schedule(delay=850){clearTimeout(timer);examples();if(!$('auto').checked)return;if(!valid()){$('status').textContent='Lengkapi isian / pilih foto untuk melihat gambar.';return;}if(lastKey===key())return;$('status').textContent='Isian berubah. Menyiapkan gambar terbaru…';timer=setTimeout(()=>render(),delay);}
async function render(){if(!valid())return;if(busy){pending=true;return;}const snapshot=key(),q=params(),path=endpoint(),p=values();busy=true;$('render').disabled=true;$('status').textContent='Membuat gambar SSGC…';try{let r;if(source==='upload'){const f=new FormData();f.append('profile',file);const large=(location.origin+'/ssgc?'+q).length>6000;if(large)for(const[k,v]of q)f.append(k,v);r=await fetch(large?'/ssgc':'/ssgc?'+q,{method:'POST',body:f});}else if((location.origin+path).length>6000)r=await fetch('/ssgc',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(q))});else r=await fetch(path);const type=r.headers.get('content-type')||'';if(!r.ok||!type.startsWith('image/')){const data=await r.json().catch(()=>({}));throw Error(data.message||'HTTP '+r.status+' — bukan gambar.');}const result=await r.blob();if(snapshot!==key())return;const old=blobUrl;blob=result;blobUrl=URL.createObjectURL(blob);$('preview').src=blobUrl;if(old)URL.revokeObjectURL(old);lastKey=snapshot;$('download').disabled=false;$('dimension').textContent=r.headers.get('X-SSGC-Width')+' × '+r.headers.get('X-SSGC-Height');$('status').textContent='Gambar sesuai isian · '+Math.round(blob.size/1024)+' KB · '+p.format.toUpperCase();$('headerValues').replaceChildren();r.headers.forEach((value,name)=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value;$('headerValues').append(dt,dd);});}
catch(e){if(snapshot===key()){$('status').textContent='Gagal: '+e.message;$('download').disabled=true;}}
finally{busy=false;$('render').disabled=false;if($('auto').checked&&(pending||snapshot!==key())){pending=false;schedule(0);}}}
async function chooseFile(f){if(!f)return;const sequence=++sourceSequence;if(f.size>2*1024*1024){$('status').textContent='Foto profil maksimum 2 MB.';return;}if(!/^image\/(jpeg|png|webp|gif|avif|bmp)$/.test(f.type)){$('status').textContent='Pilih JPEG/PNG/WebP/GIF/AVIF/BMP; SVG tidak didukung.';return;}const u=URL.createObjectURL(f),im=new Image();try{await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=reject;im.src=u;});if(im.naturalWidth*im.naturalHeight>4000000)throw Error('Foto profil maksimum 4 MP.');if(sequence!==sourceSequence)return;file=f;$('profileFileName').textContent=f.name+' · '+Math.round(f.size/1024)+' KB';sourceMode('upload');}catch(e){$('status').textContent=e.message||'Foto tidak dapat dibaca.';}finally{URL.revokeObjectURL(u);}}
function set(p){for(const k of Object.keys(defaults))$(k).value=p[k]??defaults[k];examples();schedule(200);}
$('editor').addEventListener('input',e=>{if(['profileFile','auto'].includes(e.target.id))return;schedule();});$('auto').onchange=()=>{clearTimeout(timer);if($('auto').checked)schedule(0);else $('status').textContent='Otomatis dijeda. URL/kode tetap mengikuti isian; tekan Buat gambar.';};$('editor').onsubmit=e=>{e.preventDefault();clearTimeout(timer);render();};document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>sourceMode(b.dataset.profile));$('profileFile').onchange=()=>chooseFile($('profileFile').files[0]);$('profileDrop').ondragover=e=>e.preventDefault();$('profileDrop').ondrop=e=>{e.preventDefault();chooseFile(e.dataTransfer.files[0]);};
const presets={name:{name:'Komunitas Denji',description:'Selamat datang di grup kami. ❤\nTempat berbagi cerita dan belajar bersama.',limit:'45'},full:{name:'Grup Kita',description:'Halo, selamat datang di grup kita. ❤\n'+('Tempat berbagi cerita, belajar, dan saling mendukung. '.repeat(12)),full:'1'},png:{format:'png'}};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{file=null;sourceMode('default');set(presets[b.dataset.preset]||defaults);});$('resetEditor').onclick=()=>{file=null;$('profileFile').value='';$('profileUrl').value='';$('profileFileName').textContent='Belum ada file.';sourceMode('default');lastKey='';set(defaults);};
$('copy').onclick=async()=>{const post=source==='upload'||(location.origin+endpoint()).length>6000,text=post?$('code').textContent:$('apiUrl').value;try{await navigator.clipboard.writeText(text);}catch(_){const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove();}$('status').textContent=post?'cURL POST disalin.':'URL API disalin.';};
$('download').onclick=()=>{if(!blobUrl||lastKey!==key())return;const a=document.createElement('a');a.href=blobUrl;a.download='ssgc.'+$('format').value;a.click();$('status').textContent='Gambar diunduh dari respons yang sama; tanpa request kedua.';};addEventListener('pagehide',()=>{if(blobUrl)URL.revokeObjectURL(blobUrl);});examples();schedule(150);
})();
