#!/usr/bin/env python3
"""Build the offline IQC5 template from committed fonts and photo assets."""
from pathlib import Path
import base64,json
ROOT=Path(__file__).resolve().parents[1]
ASSETS=ROOT/'api/iqc5-assets'
def uri(p,mime=None):
    p=Path(p);mime=mime or ('image/png' if p.suffix=='.png' else 'image/jpeg')
    return 'data:'+mime+';base64,'+base64.b64encode(p.read_bytes()).decode()
font=uri(ASSETS/'roboto-400.woff2','font/woff2')
fonts="@font-face{font-family:Roboto;font-style:normal;font-weight:100 900;font-display:block;src:url('"+font+"') format('woff2')}"
old=(ROOT/'api/iqc.js').read_text();formatter=old[old.index('function esc(s)'):old.index('function getTemplate2()')]
toolbar={k:uri(ROOT/'api/iqc4-assets'/('reaction-'+n+'.png')) for k,n in [('👍','58'),('❤️','115'),('😂','171'),('😮','227'),('😢','284'),('🙏','340')]}
html='''<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IQC5 · Profil & Nama</title><style>
__FONTS__
*{box-sizing:border-box}html,body{margin:0;padding:0;background:#f8f2e7;overflow-x:hidden;scrollbar-width:none}::-webkit-scrollbar{display:none}[hidden]{display:none!important}body{font-family:Roboto,Arial,sans-serif}
#frame{position:relative;width:736px;height:1308px;transform-origin:top left;overflow:hidden;background:#f8f2e7}#reference{position:absolute;inset:0;width:736px;height:1308px;display:block}#dynamic{position:absolute;inset:0}
.backdrop{position:absolute;inset:0;background:url('__BACKDROP__') center top/100% 100% no-repeat}
#tray{position:absolute;left:33px;top:451px;width:610px;height:122px;border-radius:64px;background:#252827;display:flex;align-items:center;padding:0 23px;color:#a9abab;box-shadow:0 18px 52px 13px rgba(0,0,0,.2)}
.reaction{position:relative;width:77px;height:80px;flex:0 0 77px;display:grid;place-items:center}.reaction img{position:relative;width:64px;height:65px;object-fit:contain}.reaction.selected:before{content:"";position:absolute;inset:0 0;border-radius:50%;background:#444846}.add{width:72px;height:72px;flex:0 0 72px;margin-left:30px;background:#1e2221;border-radius:50%;display:grid;place-items:center;font-size:51px;font-weight:300;line-height:1}
#bubble{position:absolute;left:94px;top:594px;min-width:170px;width:max-content;max-width:574px;border-radius:26px;padding:8px 17px 12px;background:#252827;color:#fafafa;isolation:isolate;box-shadow:12px 13px 46px 3px rgba(0,0,0,.23)}#bubble:before{content:"";position:absolute;left:-15px;bottom:0;width:29px;height:23px;background:inherit;clip-path:path('M29 0C16 5 17 14 0 23C16 23 22 20 29 17Z');z-index:-1}
#name{min-height:42px;max-width:540px;display:flex;align-items:center;margin:0 0 6px;font-size:34px;line-height:42px;font-weight:700;overflow-wrap:anywhere;color:#b83e91}#name svg{width:40px;height:40px;display:block}#msg{max-width:540px;font-size:32px;font-weight:700;line-height:36px;overflow-wrap:anywhere;white-space:normal;letter-spacing:0}#msg:after{content:"";display:inline-block;width:100px;height:1px}#msg img.apple-emoji{width:34px;height:34px;vertical-align:-6px;object-fit:contain}#msg code.wa-mono{font:90%/1.2 monospace;background:rgba(255,255,255,.12);border-radius:4px;padding:0 3px}#msg ul.wa,#msg ol.wa{padding-left:31px;margin:6px 0}#msg blockquote.wa{border-left:4px solid #c1c6c3;padding-left:12px;margin:6px 0}
.metadata{position:absolute;right:20px;bottom:10px;display:flex;align-items:center;gap:5px;color:#939896;font-size:22px;line-height:26px;font-weight:400}.metadata svg{width:16px;height:16px}
#avatar{position:absolute;left:17px;top:674px;width:60px;height:60px;border-radius:50%;overflow:hidden;background:#8f0835;display:grid;place-items:center}#avatar img{width:100%;height:100%;display:block;object-fit:cover}#avatar svg{width:32px;height:32px;color:#f4b6cd}
#badge{position:absolute;left:108px;top:725px;width:61px;height:44px;border:1px solid #454a47;border-radius:24px;background:#252827;display:grid;place-items:center;z-index:2}#badge img{width:36px;height:36px;object-fit:contain}
#menu{position:absolute;left:33px;top:754px;width:512px;height:554px;border-radius:35px;overflow:hidden;box-shadow:26px 9px 70px 9px rgba(0,0,0,.38)}#menuPhoto{width:512px;height:554px;display:block}#menuLive{height:554px;background:#252827;color:#f4f5f4}.menu-row{height:90px;display:flex;align-items:center;justify-content:space-between;padding:0 32px;border-bottom:1px solid rgba(255,255,255,.1);font-size:34px;line-height:40px;font-weight:400}.menu-row svg{width:44px;height:44px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linejoin:round;stroke-linecap:round;flex:0 0 44px}.menu-row.delete{color:#b95169}.menu-gap{height:14px;background:#1c201e}.menu-row:last-child{border:0}
.light #tray,.light #bubble,.light #badge{background:#fff;color:#151c18}.light .reaction.selected:before{background:#e5e8e7}.light .add{background:#ecedec;color:#777}.light #menuLive{background:#f2f3f1;color:#101613}.light .menu-row{border-color:rgba(0,0,0,.12)}.light .menu-gap{background:#dfe2df}.light #badge{border-color:#cdd2ce}
</style></head><body><div id="frame"><img id="reference" src="__REFERENCE__" alt="Foto IQC5 asli"><div id="dynamic" hidden><div class="backdrop"></div><div id="tray"></div><div id="bubble"><div id="name"></div><div id="msg"></div><div class="metadata"><svg id="star" viewBox="0 0 24 24" fill="currentColor" hidden><path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z"/></svg><span id="time">10:00</span></div></div>
<div id="avatar"><svg id="person" viewBox="0 0 32 32" fill="currentColor"><circle cx="16" cy="10" r="5"/><path d="M6 26v-3a10 8 0 0 1 20 0v3Z"/></svg><img id="profileImage" alt="Foto profil" hidden></div><div id="badge" hidden><img id="badgeEmoji" alt="Reaksi pesan"></div>
<div id="menu"><img id="menuPhoto" src="__MENU__" alt="Menu WhatsApp dari foto"><div id="menuLive" hidden>
<div class="menu-row"><span data-label="0">Membalas</span><svg viewBox="0 0 32 32"><path d="m14 5-10 9 10 9v-7c10 0 13 5 14 9 2-9-4-15-14-15Z"/></svg></div>
<div class="menu-row"><span data-label="1">Teruskan</span><svg viewBox="0 0 32 32"><path d="m18 5 10 9-10 9v-7C8 16 5 21 4 25 2 16 8 10 18 10Z"/></svg></div>
<div class="menu-row"><span data-label="2">Salin</span><svg viewBox="0 0 32 32"><path d="M12 5h7l6 6v15H12Z M19 5v7h6 M9 10H5v19h14v-3 M9 10V2h12v3"/></svg></div>
<div class="menu-row"><span data-label="3">Beri Bintang</span><svg viewBox="0 0 32 32"><path d="m16 3 4 9 10 1-8 7 3 10-9-6-9 6 3-10-8-7 10-1Z"/></svg></div>
<div class="menu-row delete"><span data-label="4">Hapus</span><svg viewBox="0 0 32 32"><path d="M7 8h18M12 8V4h8v4M9 8l1 20h12l1-20M14 12v12M18 12v12"/></svg></div><div class="menu-gap"></div><div class="menu-row"><span data-label="5">Lainnya...</span></div>
</div></div></div></div><script>
(function(){
__FORMATTER__
const $=id=>document.getElementById(id),defaults={message:'dikasih muka cakep , ngapain harus faker? 🤣🤤',name:'★',nameColor:'#b83e91',profileColor:'#8f0835',mode:'dark',time:'10:00',reaction:'none',star:false,menu:true,reactions:true,language:'id',profileKind:'default',profileData:''};
const toolbar=__TOOLBAR__,emojis=__EMOJIS__,keys=['👍','❤️','😂','😮','😢','🙏'];let p=__IQC5_DATA__,height=1308,sequence=0;
function fit(){const s=Math.min(1,innerWidth/736);$('frame').style.transform='scale('+s+')';document.body.style.height=Math.ceil(height*s)+'px';parent.postMessage({type:'IQC5_SIZE',width:736,height,scaledHeight:Math.ceil(height*s)},'*');}
function embedded(s){const k=Array.from(s).map(c=>c.codePointAt(0).toString(16)).join('-');return emojis[k]||emojis[k.replace(/-fe0f/g,'')]||(s==='❤'?emojis['2764-fe0f']:null);}
function emojiMessage(){const walker=document.createTreeWalker($('msg'),NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);const seg=new Intl.Segmenter('id',{granularity:'grapheme'});for(const node of nodes){const f=document.createDocumentFragment();let changed=false;for(const item of seg.segment(node.data)){const src=embedded(item.segment);if(src){const i=new Image();i.src=src;i.alt=item.segment;i.className='apple-emoji';f.append(i);changed=true;}else f.append(document.createTextNode(item.segment));}if(changed)node.replaceWith(f);}}
function normal(raw){const d={...defaults,...p,...raw};d.message=String(d.message||defaults.message).trim().slice(0,1000)||defaults.message;d.name=String(d.name||defaults.name).trim().slice(0,30)||defaults.name;for(const k of ['nameColor','profileColor'])d[k]=/^#[a-f0-9]{6}$/i.test(d[k])?d[k]:defaults[k];d.mode=d.mode==='light'?'light':'dark';d.time=/^(?:[01]?\\d|2[0-3])[.:][0-5]\\d$/.test(String(d.time))?String(d.time).replace('.',':').padStart(5,'0'):defaults.time;d.reaction=keys.includes(d.reaction)||d.reaction==='none'?d.reaction:'none';for(const k of ['star','menu','reactions'])d[k]=d[k]===false||d[k]==='0'?false:true;d.language=d.language==='en'?'en':'id';d.profileKind=['default','image','none'].includes(d.profileKind)?d.profileKind:'default';d.profileData=typeof d.profileData==='string'&&/^data:image\\/(png|jpeg|webp|gif|avif|bmp);base64,[A-Za-z0-9+/=]+$/.test(d.profileData)?d.profileData:'';return d;}
async function render(raw){const run=++sequence;window.__iqc5Ready=false;window.__iqc5Error=null;p=normal(raw);const same=Object.keys(defaults).every(k=>p[k]===defaults[k]);$('reference').hidden=!same;$('dynamic').hidden=same;$('frame').classList.toggle('light',p.mode==='light');
if(!same){$('name').replaceChildren();$('name').style.color=p.nameColor;if(p.name==='★'){const el=document.createElementNS('http://www.w3.org/2000/svg','svg');el.setAttribute('viewBox','0 0 40 40');el.setAttribute('fill','currentColor');const path=document.createElementNS(el.namespaceURI,'path');path.setAttribute('d','m20 0 5 13 15 2-11 10 3 15-12-7-12 7 3-15L0 15l15-2Z');el.append(path);$('name').append(el);}else $('name').textContent=p.name;
$('msg').innerHTML=waToHtml(p.message);emojiMessage();$('time').textContent=p.time;$('star').toggleAttribute('hidden',!p.star);$('tray').replaceChildren();for(const key of keys){const e=document.createElement('span');e.className='reaction'+(p.reaction===key?' selected':'');const i=new Image();i.src=toolbar[key];i.alt=key;e.append(i);$('tray').append(e);}const plus=document.createElement('span');plus.className='add';plus.textContent='+';$('tray').append(plus);$('tray').hidden=!p.reactions;$('badge').hidden=p.reaction==='none';if(p.reaction!=='none'){$('badgeEmoji').src=toolbar[p.reaction];$('badgeEmoji').alt=p.reaction;}
$('avatar').hidden=p.profileKind==='none';$('avatar').style.background=p.profileColor;const photo=p.profileKind==='image'&&p.profileData;$('person').toggleAttribute('hidden',Boolean(photo));$('profileImage').hidden=!photo;if(photo)$('profileImage').src=p.profileData;else $('profileImage').removeAttribute('src');
$('menu').hidden=!p.menu;const raster=p.mode==='dark'&&p.language==='id'&&!p.star;$('menuPhoto').hidden=!raster;$('menuLive').hidden=raster;const labels=p.language==='en'?['Reply','Forward','Copy',p.star?'Unstar':'Star','Delete','More...']:['Membalas','Teruskan','Salin',p.star?'Hapus Bintang':'Beri Bintang','Hapus','Lainnya...'];document.querySelectorAll('[data-label]').forEach((e,i)=>e.textContent=labels[i]);}
await document.fonts.ready;await Promise.all([...document.images].map(i=>i.complete?Promise.resolve():new Promise(r=>{i.onload=r;i.onerror=r;})));if(run!==sequence)return;if(!same&&p.profileKind==='image'&&!$('profileImage').naturalWidth){window.__iqc5Error='PROFILE_DECODE_FAILED';return;}
const h=same?140:$('bubble').offsetHeight,menuTop=594+h+20;$('avatar').style.top=(594+h-60)+'px';$('badge').style.top=(594+h-8)+'px';$('menu').style.top=menuTop+'px';height=same?1308:Math.max(1308,p.menu?menuTop+554:594+h+70);$('frame').style.height=height+'px';fit();window.__iqc5Ready=true;}
addEventListener('resize',fit);addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.type==='IQC5_UPDATE')render(e.data.data);});render(p);
})();</script></body></html>'''
html=html.replace('__FONTS__',fonts).replace('__BACKDROP__',uri(ASSETS/'backdrop.jpg')).replace('__REFERENCE__',uri(ASSETS/'reference.png')).replace('__MENU__',uri(ASSETS/'menu.png')).replace('__FORMATTER__',formatter).replace('__TOOLBAR__',json.dumps(toolbar,ensure_ascii=False,separators=(',',':'))).replace('__EMOJIS__',(ASSETS/'emojis.json').read_text())
(ROOT/'api/_template5.html').write_text(html)
print('IQC5 template:',len(html.encode()),'bytes, all assets offline')
