#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
base=(ROOT/'public/app5.html').read_text();css=base[base.index('<style>')+7:base.index('</style>')]
css+='\n.preview-shell{max-width:739px;min-height:300px;background:#0a0a0a}.preview-shell img{display:block;width:100%;height:auto}.preview-shell img:not([src]){display:none}.preview-head{max-width:739px}.description-hint{font-size:11px;line-height:1.7;color:#536832}.header-values{display:grid;grid-template-columns:minmax(0,.85fr) minmax(0,1.3fr);gap:5px 10px;font:11px/1.7 monospace}.header-values dt,.header-values dd{margin:0;overflow-wrap:anywhere}.header-values dt{font-weight:700}.button:disabled{opacity:.55;cursor:not-allowed}.nav{flex-wrap:wrap}.explore-cta .button{box-shadow:1.5px 1.5px 0 var(--line)}@media(max-width:740px){.nav{flex-wrap:nowrap;overflow-x:auto;scrollbar-width:none}.nav::-webkit-scrollbar{display:none}.nav a{flex:0 0 auto}}'
html='''<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SSGC · Info Grup WhatsApp — Denji</title><script src="/js/config.js" defer></script><style>__CSS__</style></head><body><header><div class="header-inner"><a class="brand" href="/">DENJI API <span class="badge">SSGC / GRUP</span></a><nav class="nav"><a href="/docs?playground=ssgc#playground">Playground</a><a href="/docs#ep-ssgc">Docs API</a><a href="/">Beranda</a><a href="/app5">IQC5</a><a href="/lowquality-app">Lowquality</a></nav></div></header>
<main class="layout"><section class="tools"><h1>Info grup,<br>versi kamu.</h1><p class="intro">Nama, deskripsi dan profil dari foto WhatsApp. Atur batas Baca selengkapnya atau tampilkan seluruh teks. Default JPG memakai foto asli byte-identik.</p><div class="preset-list"><button type="button" data-preset="default">Foto asli</button><button type="button" data-preset="name">Nama sendiri</button><button type="button" data-preset="full">Deskripsi penuh</button><button type="button" data-preset="png">PNG</button></div>
<form id="editor"><div class="field"><label for="name">Nama grup <code>name / nama</code></label><input id="name" maxlength="64" value="VOXEN FIGHTER"></div><div class="row"><div class="field"><label for="members">Jumlah anggota <code>members</code></label><input id="members" type="number" min="0" max="999999" step="1" value="126" required></div><div class="field"><label for="titleFont">Font nama <code>titleFont</code></label><select id="titleFont"><option value="serif">Serif · sesuai foto</option><option value="sans">Sans · Roboto</option></select></div></div>
<div class="field"><label>Foto profil <code>profile / avatar / pp</code></label><div class="profile-modes"><button type="button" data-profile="default" aria-pressed="true">Bawaan foto</button><button type="button" data-profile="upload" aria-pressed="false">Upload</button><button type="button" data-profile="url" aria-pressed="false">URL publik</button><button type="button" data-profile="none" aria-pressed="false">Tanpa foto</button></div><div id="profileUpload" hidden><label class="avatar-upload" id="profileDrop">Pilih / tarik foto ke sini (maks. 2 MB / 4 MP)<input type="file" id="profileFile" accept="image/jpeg,image/png,image/webp,image/gif,image/avif,image/bmp"></label><p class="profile-help" id="profileFileName">Belum ada file.</p></div><div id="profileUrlFields" hidden><label for="profileUrl">URL gambar publik</label><input id="profileUrl" type="url" maxlength="2048" placeholder="https://.../foto.jpg"><p class="profile-help">URL publik diambil lewat downloader aman. Localhost/private/SVG diblokir. Upload memakai POST multipart, bukan base64 di GET.</p></div></div>
<div class="field"><div class="field-top"><label for="description">Deskripsi grup <code>description / deskripsi</code></label><span class="counter" id="count">0 / 2000</span></div><textarea id="description" rows="5" maxlength="2000">WELCOME TO—VOXEN FIGHTER
#VOXEN ANTI-DIMMING...</textarea></div>
<div class="row"><div class="field"><label for="full">Tampilan deskripsi <code>full</code></label><select id="full"><option value="0">Ringkas · Baca selengkapnya</option><option value="1">Penuh · tanpa potong</option></select></div><div class="field"><label for="limit">Batas karakter <code>limit / batas</code></label><input id="limit" type="number" min="0" max="2000" step="1" value="44" required></div></div><p class="description-hint" id="descriptionHint"></p><p class="profile-help">Batas dihitung sebagai karakter/grapheme, agar emoji tidak terpotong. 0 = tampil penuh. Link hijau hanya muncul jika teks melebihi batas; menu di bawah bergeser otomatis. Mode penuh memakai tatanan inline rata tengah, wrap per kata dan spasi paragraf. *tebal*, _miring_, ~coret~, backtick dan URL hijau didukung ketika full.</p>
<div class="field"><label for="format">Format gambar <code>format</code></label><select id="format"><option value="jpg">JPG · default foto asli</option><option value="png">PNG · lossless render</option></select></div><div class="checks"><label><input id="auto" type="checkbox" checked> Pratinjau gambar otomatis</label></div><div class="actions"><button type="submit" class="button" id="render">Buat gambar</button><button type="button" class="button secondary" id="download" disabled>↓ Unduh gambar</button><button type="button" class="button secondary" id="copy">Salin URL / cURL</button></div><div class="small-links"><button type="button" id="resetEditor" style="border:0;background:none;padding:0;font:inherit;color:inherit;text-decoration:underline;cursor:pointer">Reset foto asli</button></div><div class="status" id="status" role="status" aria-live="polite"></div><p class="note">Default deskripsi berisi teks yang terlihat pada foto; bagian tersembunyi tidak tersedia dari screenshot. Masukkan deskripsi lengkap sendiri untuk memakai mode penuh. Tampilan ini gambar statis, bukan grup WhatsApp aktif.</p><div class="explore-cta" style="margin-top:18px"><div class="explore-title">Lanjut eksplor?</div><div class="explore-desc">Coba generator lain atau buka dokumentasi lengkap. Semua preview memakai respons yang sama tanpa request kedua.</div><div style="display:flex;flex-wrap:wrap;gap:8px"><a class="button secondary" href="/app5">IQC5 Profil</a><a class="button secondary" href="/lowquality-app">Lowquality JPEG</a><a class="button secondary" href="/docs#ep-ssgc">Docs SSGC</a><a class="button secondary" href="/docs#playground">Playground</a></div></div></form></section>
<section><div class="preview-head"><h2>PRATINJAU GAMBAR</h2><span class="preview-tag" id="dimension">739 × 1600</span></div><div class="preview-shell"><img id="preview" alt="Hasil SSGC sesuai isian"></div><div class="api-panel"><label for="apiUrl">Request sesuai isian</label><input id="apiUrl" readonly><pre id="code"></pre><details><summary>Header respons asli</summary><dl class="header-values" id="headerValues"></dl></details><p class="note">GET <code>/ssgc?name=Grup&amp;description=Halo&amp;limit=80</code>. Foto upload: POST multipart field <code>profile</code>. <code>full=1</code> / <code>limit=0</code> menampilkan semua deskripsi. Preview dan unduh menggunakan respons yang sama.</p></div></section></main><script>__JS__</script></body></html>'''
html=html.replace('__CSS__',css).replace('__JS__',(ROOT/'src/ui/ssgc-editor.js').read_text())
(ROOT/'public/ssgc-app.html').write_text(html);(ROOT/'ssgc-app.html').write_text(html)
print('SSGC editor:',len(html.encode()),'bytes; root/public mirrors identical.')
