from pathlib import Path
root=Path(__file__).resolve().parents[1];s=(root/'public/app4.html').read_text();css=s[s.index('<style>')+7:s.index('</style>')]
css+='\n.field input[type=color]{height:40px;padding:4px}.profile-modes{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.profile-modes button{font:inherit;font-size:11px;border:1px solid var(--line);border-radius:6px;background:#faffeb;padding:6px 8px;cursor:pointer}.profile-modes button[aria-pressed=true]{background:var(--green)}.profile-source[hidden]{display:none}.profile-help{font-size:11px;color:var(--muted);margin:5px 0}.avatar-upload{display:block;border:1px dashed var(--line);padding:12px;border-radius:9px;background:#f5f8e5;font-size:12px;cursor:pointer}.avatar-upload input{margin-top:8px;width:100%}.profile-url-row{display:flex;gap:6px}.profile-url-row input{min-width:0}.profile-url-row button{font-size:11px;white-space:nowrap}.preview-shell{max-width:736px}.preview-head{max-width:736px}.checks{grid-template-columns:repeat(2,minmax(0,1fr))}'
html='''<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IQC5 · Profil & Nama — Denji</title><script src="/js/config.js" defer></script><style>__CSS__</style></head><body>
<header><div class="header-inner"><a class="brand" href="/">DENJI API <span class="badge">IQC5 / PROFIL</span></a><nav class="nav"><a href="/docs?playground=iqc5#playground">Playground</a><a href="/docs#ep-iqc5">Docs API</a><a href="/app4">IQC4</a></nav></div></header>
<main class="layout"><section class="tools"><h1>Nama, profil,<br>dan ceritamu.</h1><p class="intro">Tampilan WhatsApp dari foto: bubble bernama, avatar bulat, reaksi, dan menu Indonesia. Default memakai PNG asli 100% identik.</p>
<div class="preset-list"><button type="button" data-preset="default">Foto asli</button><button type="button" data-preset="name">Nama Denji</button><button type="button" data-preset="profile">Profil contoh</button><button type="button" data-preset="light">Terang</button><button type="button" data-preset="long">Pesan panjang</button><button type="button" data-preset="minimal">Tanpa menu</button></div>
<form id="editor">
<div class="row"><div class="field"><label for="name">Nama <code>name / nama</code></label><input id="name" maxlength="30" value="★"><p class="profile-help">Bintang pink pada foto menjadi nama default. Bisa diganti nama sendiri.</p></div><div class="field"><label for="nameColor">Warna nama <code>nameColor</code></label><input type="color" id="nameColor" value="#b83e91"></div></div>
<div class="field"><label>Foto profil <code>profile / avatar / pp</code></label><div class="profile-modes"><button type="button" data-profile="default" aria-pressed="true">Bawaan</button><button type="button" data-profile="upload" aria-pressed="false">Upload</button><button type="button" data-profile="url" aria-pressed="false">URL publik</button><button type="button" data-profile="none" aria-pressed="false">Tanpa profil</button></div>
<div id="profileDefault" class="profile-source"><label for="profileColor">Warna avatar bawaan <code>profileColor</code></label><input type="color" id="profileColor" value="#8f0835"></div>
<div id="profileUpload" class="profile-source" hidden><label class="avatar-upload" id="profileDrop">Pilih / tarik foto ke sini (maks. 2 MB, 4 MP)<input type="file" id="profileFile" accept="image/jpeg,image/png,image/webp,image/gif,image/avif,image/bmp"></label><p class="profile-help" id="profileFileName">Belum ada file. File tidak disimpan ke localStorage.</p></div>
<div id="profileUrlFields" class="profile-source" hidden><label for="profileUrl">URL gambar publik</label><div class="profile-url-row"><input id="profileUrl" type="url" placeholder="https://.../foto.jpg" maxlength="2048"><button type="button" class="button secondary" id="applyProfile">Terapkan</button></div><p class="profile-help">URL divalidasi server; alamat private/localhost diblokir. Tekan Terapkan untuk preview profil URL.</p></div></div>
<div class="field"><div class="field-top"><label for="message">Isi pesan <code>pesan / message</code></label><span class="counter" id="count">0 / 1000</span></div><textarea id="message" rows="4" maxlength="1000">dikasih muka cakep , ngapain harus faker? 🤣🤤</textarea><p class="profile-help">Enter, emoji, *tebal*, _miring_, ~coret~, kode, daftar dan kutipan. Bubble, profil dan menu mengikuti panjang pesan.</p></div>
<div class="row"><div class="field"><label for="mode">Tema <code>mode</code></label><select id="mode"><option value="dark">Gelap · sesuai foto</option><option value="light">Terang</option></select></div><div class="field"><label for="reaction">Reaksi pesan <code>reaction</code></label><select id="reaction"><option value="none">Tanpa reaksi · foto</option><option value="❤️">❤️ Love</option><option value="👍">👍 Like</option><option value="😂">😂 Haha</option><option value="😮">😮 Wow</option><option value="😢">😢 Sedih</option><option value="🙏">🙏 Terima kasih</option></select></div></div>
<div class="row"><div class="field"><label for="time">Jam pesan <code>time</code></label><input id="time" value="10:00" maxlength="5" pattern="([01]?[0-9]|2[0-3])[.:][0-5][0-9]"></div><div class="field"><label for="language">Bahasa menu <code>lang</code></label><select id="language"><option value="id">Indonesia · sesuai foto</option><option value="en">English</option></select></div></div>
<div class="field"><label for="format">Format unduh <code>format</code></label><select id="format"><option value="png">PNG · lossless, default persis</option><option value="jpg">JPG · lebih kecil</option></select></div>
<div class="checks"><label><input type="checkbox" id="star"> Bintang pesan <code>star</code></label><label><input type="checkbox" id="menu" checked> Menu <code>menu</code></label><label><input type="checkbox" id="reactions" checked> Bar reaksi <code>reactions</code></label></div>
<div class="actions"><button class="button" type="submit" id="download">↓ Unduh gambar</button><button class="button secondary" type="button" id="copy">Salin URL / cURL</button></div>
<div class="small-links"><button type="button" id="resetEditor" style="border:0;background:none;padding:0;font:inherit;color:inherit;text-decoration:underline;cursor:pointer">Reset foto asli</button><a id="openImage" href="/iqc5" target="_blank" rel="noopener">Buka gambar ↗</a></div>
<div class="status" id="status" role="status" aria-live="polite"></div><p class="note"><strong>100% identik berlaku untuk PNG default.</strong> Setelah diubah, kartu dirender ulang dengan Roboto, latar/menu dari foto dan emoji RGBA transparan. Avatar foto dipotong lingkaran otomatis. Format JPG adalah konversi lossy, bukan file asli.</p>
</form></section><section><div class="preview-head"><h2>PRATINJAU LANGSUNG</h2><span class="preview-tag" id="dimension">736 × 1308</span></div><div class="preview-shell"><iframe id="preview" title="Pratinjau IQC5" src="/iqc5?html=1"></iframe></div><div class="api-panel"><label for="apiUrl">Request siap pakai</label><input id="apiUrl" readonly><pre id="code"></pre><p class="note">GET <code>/iqc5?name=Denji&amp;pesan=Halo&amp;profile=URL</code>. Upload profil memakai POST multipart. Alias <code>/api/iqc5</code>, <code>/qc5</code>, <code>/api/qc5</code>. Query mengoverride body.</p></div></section></main>
<script>
(function(){const $=id=>document.getElementById(id),frame=$('preview');const defaults={name:'★',message:'dikasih muka cakep , ngapain harus faker? 🤣🤤',nameColor:'#b83e91',profileColor:'#8f0835',mode:'dark',time:'10:00',reaction:'none',star:false,menu:true,reactions:true,language:'id',format:'png'};let source='default',file=null,fileData='',blobPreview=null,profileSequence=0;
function data(){const d={};for(const k of Object.keys(defaults))d[k]=['star','menu','reactions'].includes(k)?$(k).checked:$(k).value;return d;}
function parameters(d){return {name:d.name,pesan:d.message,nameColor:d.nameColor,profileColor:d.profileColor,mode:d.mode,time:d.time,reaction:d.reaction,star:d.star?'1':'0',menu:d.menu?'1':'0',reactions:d.reactions?'1':'0',lang:d.language,format:d.format};}
function endpoint(d,html=false){if(source==='default'&&Object.keys(defaults).every(k=>d[k]===defaults[k])&&!html)return '/iqc5';const q=new URLSearchParams(parameters(d));if(source==='url'&&$('profileUrl').value.trim())q.set('profile',$('profileUrl').value.trim());if(source==='none')q.set('profile','none');if(html)q.set('html','1');return '/iqc5?'+q;}
function update(){const d=data(),preview={...d};if(source==='upload'){preview.profileKind=fileData?'image':'default';preview.profileData=fileData;}else if(source==='none'){preview.profileKind='none';preview.profileData='';}else if(source==='default'){preview.profileKind='default';preview.profileData='';}frame.contentWindow.postMessage({type:'IQC5_UPDATE',data:preview},location.origin);$('count').textContent=d.message.length+' / 1000';$('apiUrl').value=source==='upload'?'POST multipart '+location.origin+'/iqc5':location.origin+endpoint(d);$('openImage').hidden=source==='upload';$('openImage').href=endpoint(d);let code;const shell=v=>"'"+String(v).replace(/'/g,"'\\\\''")+"'";if(source==='upload'){code=['curl --fail --show-error '+shell(location.origin+'/iqc5'),'  -F '+shell('profile=@foto.png'),...Object.entries(parameters(d)).map(([k,v])=>'  -F '+shell(k+'='+v)),'  -o '+shell('iqc5.'+d.format)].join(String.fromCharCode(32,92,10));}else code='curl --fail --show-error '+shell(location.origin+endpoint(d))+' -o '+shell('iqc5.'+d.format);$('code').textContent=code;}
function modeProfile(next){profileSequence++;source=next;document.querySelectorAll('[data-profile]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.profile===next)));$('profileDefault').hidden=next!=='default';$('profileUpload').hidden=next!=='upload';$('profileUrlFields').hidden=next!=='url';update();}
async function selectFile(f){if(!f)return;const sequence=++profileSequence;if(f.size>2*1024*1024){$('status').textContent='Foto profil maksimum 2 MB.';return;}if(!/^image\\/(jpeg|png|webp|gif|avif|bmp)$/.test(f.type)){$('status').textContent='Pilih gambar raster JPEG/PNG/WebP/GIF/AVIF/BMP.';return;}const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});const im=new Image();await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=reject;im.src=data;}).catch(()=>{$('status').textContent='Foto tidak dapat dibaca.';});if(!im.naturalWidth)return;if(im.naturalWidth*im.naturalHeight>4000000){$('status').textContent='Foto profil maksimum 4 MP.';return;}if(sequence!==profileSequence)return;file=f;fileData=data;$('profileFileName').textContent=f.name+' · '+Math.round(f.size/1024)+' KB';modeProfile('upload');$('status').textContent='Profil dipratinjau lokal. File baru dikirim saat unduh.';}
function set(d){for(const k of Object.keys(defaults)){const v=d[k]??defaults[k];if(['star','menu','reactions'].includes(k))$(k).checked=v;else $(k).value=v;}update();}
$('editor').addEventListener('input',e=>{if(e.target.id==='profileFile')return;if(e.target.id==='profileUrl')profileSequence++;update();});frame.addEventListener('load',update);addEventListener('message',e=>{if(e.origin===location.origin&&e.source===frame.contentWindow&&e.data?.type==='IQC5_SIZE'){frame.style.height=e.data.scaledHeight+'px';$('dimension').textContent='736 × '+e.data.height;}});
document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>modeProfile(b.dataset.profile));$('profileFile').onchange=()=>selectFile($('profileFile').files[0]);$('profileDrop').ondragover=e=>e.preventDefault();$('profileDrop').ondrop=e=>{e.preventDefault();selectFile(e.dataTransfer.files[0]);};
$('applyProfile').onclick=async()=>{const sequence=++profileSequence;const url=$('profileUrl').value.trim();if(!url){$('status').textContent='Masukkan URL gambar publik.';return;}const button=$('applyProfile');button.disabled=true;$('status').textContent='Memvalidasi URL profil di server…';try{const r=await fetch(endpoint(data(),true));if(!r.ok){const j=await r.json();throw Error(j.message||'HTTP '+r.status);}const html=await r.text();if(sequence!==profileSequence||source!=='url')return;const old=blobPreview;blobPreview=URL.createObjectURL(new Blob([html],{type:'text/html'}));frame.src=blobPreview;if(old)URL.revokeObjectURL(old);$('status').textContent='Profil URL siap. Tidak ada foto yang disimpan di server.';}catch(e){$('status').textContent='Gagal: '+e.message;}finally{button.disabled=false;update();}};
const presets={name:{name:'Denji',message:'Halo, ini nama dan ceritaku. ❤'},light:{name:'Denji',mode:'light',message:'Selamat menikmati hari yang baik. ✨',reaction:'👍'},long:{name:'Sahabat',message:'*Catatan untuk diri sendiri*\\n'+('Kamu sudah berusaha, tetap berjalan pelan-pelan. '.repeat(15))},minimal:{name:'Denji',message:'Pesan tanpa menu.',menu:false,reactions:false}};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=async()=>{file=null;fileData='';modeProfile('default');set(presets[b.dataset.preset]||{});if(b.dataset.preset==='profile'){set({name:'Denji',message:'Halo, ini profil dan namaku. ❤'});const sequence=profileSequence;const r=await fetch('/images/iqc5-avatar-demo.png');const image=await r.blob();if(sequence!==profileSequence)return;await selectFile(new File([image],'avatar-demo.png',{type:'image/png'}));}$('status').textContent=b.dataset.preset==='default'?'Kembali ke file foto asli.':'Contoh diterapkan.';});
$('resetEditor').onclick=()=>{file=null;fileData='';$('profileFile').value='';$('profileUrl').value='';$('profileFileName').textContent='Belum ada file.';modeProfile('default');set(defaults);$('status').textContent='Kembali ke PNG asli identik.';};
$('copy').onclick=async()=>{const text=source==='upload'?$('code').textContent:$('apiUrl').value;try{await navigator.clipboard.writeText(text);}catch{const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove();}$('status').textContent=source==='upload'?'cURL upload disalin.':'URL API disalin.';};
$('editor').onsubmit=async e=>{e.preventDefault();if(source==='upload'&&!file){$('status').textContent='Pilih foto profil terlebih dahulu.';return;}if(source==='url'&&!$('profileUrl').value.trim()){$('status').textContent='Masukkan URL foto profil.';return;}const button=$('download');button.disabled=true;$('status').textContent='Membuat satu gambar di server…';try{const d=data();let r;if(source==='upload'){const form=new FormData();form.append('profile',file);for(const [k,v] of Object.entries(parameters(d)))form.append(k,v);r=await fetch('/iqc5',{method:'POST',body:form});}else r=await fetch(endpoint(d));if(!r.ok){const j=await r.json();throw Error(j.message||'HTTP '+r.status);}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='iqc5.'+d.format;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);$('status').textContent='Berhasil mengunduh '+d.format.toUpperCase()+' ('+Math.round(blob.size/1024)+' KB).';}catch(e){$('status').textContent='Gagal: '+e.message;}finally{button.disabled=false;}};
update();})();</script></body></html>'''
html=html.replace('__CSS__',css);(root/'public/app5.html').write_text(html);(root/'app5.html').write_text(html)
print('IQC5 editor',len(html.encode()))
