// SSGC editor + separate sixth model in the shared image Playground.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {prepareChromium}=require('../src/services/iqc-runtime');
const base=(process.env.BASE_URL||'http://127.0.0.1:3000').replace(/\/$/,''),dir=process.env.QA_DIR||'/home/user/qa/ssgc';fs.mkdirSync(dir,{recursive:true});
let total=0;function ok(label,value=true){assert(value,label);total++;console.log('PASS '+label);}
const input=(p,id,v)=>p.$eval('#'+id,(e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},v);
async function readyEditor(p){await p.waitForFunction(()=>document.getElementById('preview')?.naturalWidth===739&&!document.getElementById('download').disabled&&!document.getElementById('render').disabled&&document.getElementById('status').textContent.startsWith('Gambar sesuai'),{timeout:70000});}
async function readyPlayground(p,description){await p.waitForFunction(desc=>{const i=document.querySelector('#pgResponseCode img');if(!i?.naturalWidth||document.getElementById('pgSubmitBtn').disabled||!document.getElementById('pgStatusBadge').textContent.includes('200'))return false;return pgIqc.info(i.dataset.endpoint)?.type==='ssgc'&&i.dataset.requestKey===pgIqc.requestKey()&&(desc===null||new URL(i.dataset.endpoint,location.origin).searchParams.get('description')===desc);},{timeout:70000},description??null);}
(async()=>{const r=await prepareChromium(),b=await r.puppeteer.launch({args:r.chromium.args,env:r.env,executablePath:r.executablePath,headless:'shell',defaultViewport:{width:1600,height:1000}});try{
const p=await b.newPage(),errors=[],calls=[],active=new Set();let concurrent=0,maxConcurrent=0;
p.on('pageerror',e=>errors.push(e.message));p.on('request',req=>{if(/^\/(api\/)?ssgc\/?$/.test(new URL(req.url()).pathname)){calls.push({url:req.url(),method:req.method(),body:req.postData()});active.add(req);concurrent++;maxConcurrent=Math.max(maxConcurrent,concurrent);}});for(const event of ['requestfinished','requestfailed'])p.on(event,req=>{if(active.delete(req))concurrent--;});
await p.goto(base+'/ssgc-app',{waitUntil:'load'});await readyEditor(p);ok('Editor default menghasilkan JPG asli 739×1600',await p.$eval('#preview',i=>i.naturalWidth===739&&i.naturalHeight===1600));
ok('Default nama/deskripsi/batas terisi',await p.evaluate(()=>document.getElementById('name').value==='VOXEN FIGHTER'&&document.getElementById('description').value.includes('#VOXEN ANTI-DIMMING...')&&document.getElementById('limit').value==='44'));
await input(p,'name','Komunitas Denji ❤');await input(p,'description','Tempat berbagi cerita, belajar dan saling mendukung bersama-sama. ❤');await input(p,'limit','25');await readyEditor(p);ok('Editor otomatis memperbarui nama/deskripsi/limit',calls.at(-1).url.includes('limit=25'));
ok('Editor memakai metadata pemotongan aktual',await p.$eval('#headerValues',e=>e.textContent.includes('x-ssgc-description-shown25')&&e.textContent.includes('x-ssgc-truncated1')));
ok('cURL mengikuti nama/deskripsi/batas',await p.$eval('#code',e=>e.textContent.includes('limit=25')&&e.textContent.includes('Komunitas')));
await input(p,'full','1');await input(p,'description',('Halo semuanya ❤. Tempat berbagi cerita, belajar dan mendukung.\n').repeat(15));await readyEditor(p);ok('Editor mode full: tinggi otomatis',await p.$eval('#preview',i=>i.naturalHeight>1600));ok('Mode full menonaktifkan batas dan header cut=0',await p.evaluate(()=>document.getElementById('limit').disabled&&document.getElementById('headerValues').textContent.includes('x-ssgc-truncated0')));
await input(p,'description','❤'.repeat(900));await readyEditor(p);ok('Editor payload panjang otomatis POST JSON, tanpa URL panjang',calls.at(-1).method==='POST'&&!new URL(calls.at(-1).url).search&&JSON.parse(calls.at(-1).body).description==='❤'.repeat(900));ok('cURL editor payload panjang memakai body JSON',await p.$eval('#code',e=>e.textContent.includes('--data-raw')&&e.textContent.includes('Content-Type: application/json')));
await p.$eval('#auto',e=>{e.checked=false;e.dispatchEvent(new Event('change'));});const paused=calls.length;await input(p,'description','Editor dijeda '+Date.now());await new Promise(r=>setTimeout(r,1150));ok('Editor pause tidak mengirim request',calls.length===paused);ok('Download lama tidak tersedia setelah isian berubah',await p.$eval('#download',e=>e.disabled));await p.$eval('#editor',e=>e.requestSubmit());await readyEditor(p);ok('Tombol manual tetap menghasilkan gambar');
await p.$eval('#auto',e=>{e.checked=true;e.dispatchEvent(new Event('change'));});await p.locator('[data-profile="upload"]').click();await(await p.$('#profileFile')).uploadFile(path.join(__dirname,'../public/images/iqc5-avatar-demo.png'));await readyEditor(p);ok('Editor upload memakai POST multipart',calls.at(-1).method==='POST');ok('cURL upload memakai nama file pilihan',await p.$eval('#code',e=>e.textContent.includes('profile=@iqc5-avatar-demo.png')));
await p.locator('[data-profile="url"]').click();await input(p,'profileUrl','https://jpeg.wavebeem.com/icon.jpg');await readyEditor(p);ok('Editor profil URL publik otomatis',new URL(calls.at(-1).url).searchParams.get('profile')==='https://jpeg.wavebeem.com/icon.jpg');
await p.locator('[data-profile="none"]').click();await input(p,'format','png');await readyEditor(p);ok('Editor tanpa profil + PNG',await p.$eval('#status',e=>e.textContent.includes('PNG')));ok('Nama unduhan/kode PNG benar',await p.$eval('#code',e=>e.textContent.includes('ssgc.png')));
await p.$eval('#resetEditor',e=>e.click());await readyEditor(p);ok('Reset kembali ke foto asli tanpa kehilangan default',new URL(calls.at(-1).url).pathname==='/ssgc'&&!new URL(calls.at(-1).url).search);
const before=calls.length;await p.$eval('#download',e=>e.click());await new Promise(r=>setTimeout(r,150));ok('Unduh editor memakai blob yang sama, bukan render kedua',calls.length===before);
await p.screenshot({path:path.join(dir,'editor-desktop.png'),fullPage:true});
for(const width of [320,390,768,1024,1440,1920]){await p.setViewport({width,height:900});ok('Editor tanpa overflow '+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
await p.setViewport({width:390,height:844});await p.screenshot({path:path.join(dir,'editor-mobile.png'),fullPage:true});
await p.setViewport({width:1600,height:1000});await p.goto(base+'/docs?playground=ssgc#playground',{waitUntil:'load'});await readyPlayground(p);ok('SSGC model terpisah: enam model tanpa IQC6',await p.$$eval('[data-iqc-type]',a=>a.length===6&&a.some(e=>e.dataset.iqcType==='ssgc')&&!a.some(e=>e.dataset.iqcType==='iqc6')));
ok('Kontrol khusus grup terlihat; kontrol IQC5 disembunyikan',await p.evaluate(()=>!document.getElementById('pgIqcSsgc').hidden&&document.getElementById('pgIqcProfileNote').hidden&&document.getElementById('pgIqcWa').hidden));
ok('Batas input name64/description2000',await p.evaluate(()=>document.getElementById('pgIqcName').maxLength===64&&document.getElementById('pgIqcText').maxLength===2000));
ok('Guide/default/header SSGC tersedia',await p.evaluate(()=>document.getElementById('pgIqcDefaultValues').textContent.includes('VOXEN FIGHTER')&&document.getElementById('pgIqcHeaderReference').textContent.includes('X-SSGC-Truncated')&&document.getElementById('iqc-headers-reference').textContent.includes('SSGC')));
const description='Halo grup. Tempat berbagi cerita dan saling membantu. ❤ '+Date.now();await input(p,'pgIqcName','Grup Kita ❤');await input(p,'pgIqcText',description);await input(p,'pgIqcSsgcLimit','12');await input(p,'pgIqcSsgcMembers','543');await input(p,'pgIqcSsgcTitleFont','sans');await readyPlayground(p,description);ok('Playground edit otomatis menjadi gambar JPG');
const params=await p.$eval('#pgEndpoint',e=>Object.fromEntries(new URL(e.value,location.origin).searchParams));ok('URL berisi seluruh parameter grup aktual',params.name==='Grup Kita ❤'&&params.description===description&&params.limit==='12'&&params.members==='543'&&params.titleFont==='sans'&&params.format==='jpg');
for(const language of ['curl','javascript','python','php','go']){const code=await p.evaluate(l=>pgIqc.generated(l),language);ok('Contoh '+language+' mengikuti name/description/limit/format',(code.includes('Grup Kita')||code.includes('Grup+Kita')||code.includes('Grup%20Kita'))&&(code.includes(description)||code.includes(encodeURIComponent(description))||code.includes(new URLSearchParams({description}).toString().slice(12)))&&code.includes('12')&&code.includes('ssgc.jpg'));}
ok('Panel respons asli mencatat semua metadata SSGC',await p.$eval('#pgResponseInfo',e=>e.textContent.includes('x-ssgc-truncated1')&&e.textContent.includes('x-ssgc-description-shown12')&&e.textContent.includes('image/jpeg')));
await input(p,'pgIqcSsgcFull','1');const long=('Tempat berbagi cerita, belajar bersama dan saling mendukung ❤.\n').repeat(16);await input(p,'pgIqcText',long);await readyPlayground(p,long.trim());ok('Playground full otomatis menambah tinggi',await p.$eval('#pgResponseCode img',e=>e.naturalHeight>1600));ok('Limit disabled pada full',await p.$eval('#pgIqcSsgcLimit',e=>e.disabled));
await input(p,'pgIqcSsgcFormat','png');await readyPlayground(p,long.trim());ok('Format PNG preview/unduh/kode sesuai',await p.evaluate(()=>document.querySelector('#pgResponseCode .res-download').download==='ssgc.png'&&pgIqc.generated('curl').includes('ssgc.png')));
const heavy='❤'.repeat(900);await input(p,'pgIqcText',heavy);await readyPlayground(p,heavy);ok('Playground payload panjang otomatis POST JSON',calls.at(-1).method==='POST'&&!new URL(calls.at(-1).url).search&&JSON.parse(calls.at(-1).body).description===heavy);for(const language of ['curl','javascript','python','php','go'])ok('Contoh JSON panjang '+language+' mengikuti body aktual',await p.evaluate(({language,heavy})=>{const c=pgIqc.generated(language);return c.toLowerCase().includes('post')&&c.includes(heavy)&&c.includes('ssgc.png');},{language,heavy}));
await p.evaluate(()=>pgIqc.pause());await input(p,'pgIqcProfileSource','upload');await(await p.$('#pgIqcProfileFile')).uploadFile(path.join(__dirname,'../public/images/iqc5-avatar-demo.png'));ok('Playground upload mengunci POST dan memakai filename',await p.evaluate(()=>document.getElementById('pgMethod').value==='POST'&&pgIqc.generated('curl').includes('profile=@iqc5-avatar-demo.png')));
await p.evaluate(()=>executePlayground({preventDefault(){}}));await readyPlayground(p,heavy);ok('Playground POST profil panjang di multipart tanpa URL panjang',calls.at(-1).method==='POST'&&!new URL(calls.at(-1).url).search);
for(const language of ['curl','javascript','python','php','go'])ok('Contoh upload '+language+' memakai file aktual',await p.evaluate(l=>pgIqc.generated(l).includes('iqc5-avatar-demo.png'),language));
await p.evaluate(()=>pgIqc.reset());ok('Reset Playground lengkap: source/name/limit/full/format',await p.evaluate(()=>document.getElementById('pgIqcProfileSource').value==='default'&&document.getElementById('pgIqcName').value==='VOXEN FIGHTER'&&document.getElementById('pgIqcSsgcLimit').value==='44'&&document.getElementById('pgIqcSsgcFull').value==='0'&&document.getElementById('pgIqcSsgcFormat').value==='jpg'));
await p.$eval('#pgIqcAuto',e=>{e.checked=true;e.dispatchEvent(new Event('change'));});await readyPlayground(p);ok('Reset guide kembali ke GET setelah payload POST panjang',await p.$eval('#pgIqcHowTo',e=>e.textContent.startsWith('GET')));await p.$eval('#playground',e=>e.scrollIntoView({behavior:'instant'}));await p.screenshot({path:path.join(dir,'playground-desktop.png')});
for(const width of [320,390,768,1024,1440,1920]){await p.setViewport({width,height:900});ok('Playground SSGC tanpa overflow '+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
await p.setViewport({width:390,height:844});await p.$eval('#playground',e=>e.scrollIntoView({behavior:'instant'}));await p.screenshot({path:path.join(dir,'playground-mobile.png')});
await p.evaluate(()=>pgIqc.pause());await input(p,'pgIqcText','State SSGC tersimpan');await input(p,'pgIqcSsgcLimit','8');await p.evaluate(()=>history.replaceState(null,'','/docs#playground'));await p.reload({waitUntil:'load'});ok('State grup tersimpan lintas reload',await p.evaluate(()=>document.getElementById('pgIqcText').value==='State SSGC tersimpan'&&document.getElementById('pgIqcSsgcLimit').value==='8'));
await p.evaluate(()=>pgIqc.select('iqc5'));ok('Berpindah IQC5 mengembalikan kontrol lama',await p.evaluate(()=>document.getElementById('pgIqcSsgc').hidden&&!document.getElementById('pgIqcProfileNote').hidden&&document.getElementById('pgIqcName').maxLength===30&&document.getElementById('pgIqcText').maxLength===1000));
ok('Editor/Playground SSGC maksimal satu request aktif',maxConcurrent<=1);
// Check actual template DOM, not only server-side count metadata.
const t=await b.newPage();t.on('pageerror',e=>errors.push(e.message));
for(const [description,limit,full,shown,cut] of [['ABCDE',5,0,'ABCDE',false],['ABCDE',4,0,'ABCD',true],['ABCDE',1,1,'ABCDE',false],['ABCDE',0,0,'ABCDE',false],['',44,0,'',false],['A👨‍👩‍👧‍👦🇮🇩e\u0301Z',3,0,'A👨‍👩‍👧‍👦🇮🇩',true]]){
await t.goto(base+'/ssgc?'+new URLSearchParams({description,limit,full,html:1}),{waitUntil:'load'});await t.waitForFunction(()=>window.__ssgcReady,{timeout:15000});ok('DOM: batas '+limit+', full '+full+', cut '+cut,await t.evaluate(({shown,cut})=>window.__ssgcDescription.visible===shown&&window.__ssgcDescription.truncated===cut&&document.getElementById('more').hidden===!cut,{shown,cut}));}
await t.goto(base+'/ssgc?'+new URLSearchParams({name:'GRUP KITA BERSAMA '.repeat(4),description:long,full:1,html:1}),{waitUntil:'load'});await t.waitForFunction(()=>window.__ssgcReady,{timeout:15000});ok('DOM: nama/anggota/deskripsi/menu tidak bertumpuk',await t.evaluate(()=>{const r=id=>document.getElementById(id).getBoundingClientRect();return r('name').bottom<=r('members').top&&r('members').bottom<=r('description').top&&r('description').bottom<r('footer').top&&r('footer').bottom<=r('frame').bottom;}));
await t.screenshot({path:path.join(dir,'template-full.png'),fullPage:true});await t.close();ok('Tidak ada JavaScript error',errors.length===0);console.log('TOTAL '+total+' PASS');
}finally{await b.close();}})().catch(e=>{console.error('FAIL',e.stack);process.exitCode=1;});
